### ISSUE TITLE
Fix build for IE9

### ISSUE THREAD

**Issue by mashhoodr** [recurship/angular2-multicomponent-form#2]
https://christianliebel.com/2016/03/fixing-angular-2-app-ie-9-11/

**Comment by mashhoodr** [comment]
@narainsagar @ZenabKhan was already working on this.  please take over her branch as she is busy with another project. rebase it and then we can start fixing it

**Comment by narainsagar** [comment]
ok.

**Comment by narainsagar** [comment]
Completed in PR #11
